import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  toolsSidebar: [
    'intro',
    'getting-started',
    {
      type: 'category',
      label: 'All tools',
      link: {type: 'doc', id: 'tools/index'},
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'tools'}],
    },
    {
      type: 'category',
      label: 'Guides',
      link: {type: 'doc', id: 'guides/index'},
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'guides'}],
    },
    'privacy',
    'changelog',
  ],
};

export default sidebars;
